apiVersion: v1
kind: Pod
metadata:
  name: myapp2
  labels:
    name: myapp2
spec:
  containers:
  - name: myapp2
    image: prateekkumawat/static:19
    resources:
    limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
