apiVersion: v1
kind: Pod
metadata:
  name: nginx-store
  labels:
    name: nginx-store
spec:
  volumes:
  - name: web-content
    hostPath:
      path: "/data/nginx-store"
      type: Directory
  containers:
  - name: nginx-store
    image: nginx:latest
    resources:
    ports:
      - containerPort: 80
    volumeMounts:
    - name: web-content
      mountPath: /usr/share/nginx/html  