apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-dynamic-store-pvc
  labels:
    app: nginx-dynamic-store
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
