apiVersion: v1
kind: Service
metadata:
  name: nginx-dynamic-store-svc
  labels:
    app: nginx-dynamic-store
spec:
  selector:
    app: nginx-dynamic-store
    type: ClusterIP
  ports:
  - name: nginx-service
    port: 80
    targetPort: 80
